version: '3.7'

services:
  server1:
    build:
      context: ./server
    ports:
      - "3001:3000"

  server2:
    build:
      context: ./server
    ports:
      - "3002:3000"

  load-balancer:
    image: nginx:latest
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
